version: '3.9'

x-php: &php
  user: www-data
  build:
    context: ./
    dockerfile: ./docker/php/Dockerfile
    target: development
  restart: unless-stopped
  depends_on:
    - wiremock
  volumes:
    - .:/data
  networks:
    - functional-tests-network


services:
  db:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: functionaltests
        MYSQL_USER: dev
        MYSQL_PASSWORD: dev
      ports:
        - '4306:3306'
      volumes:
        - db_data:/var/lib/mysql
      networks:
        - functional-tests-network

  php:
    <<: *php
    expose:
      - 9000

  nginx:
    hostname: web
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8080:80"
    expose:
      - 80
    volumes:
      - ./public:/data/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - functional-tests-network

  rabbitmq:
    image: rabbitmq:3.9-management
    environment:
      RABBITMQ_DEFAULT_USER: dev
      RABBITMQ_DEFAULT_PASS: dev
    networks:
      - functional-tests-network

  wiremock:
    image: "wiremock/wiremock:latest"
    ports:
      - 8090:8080
      - 9999:9999
    expose:
      - 8090
      - 8080
      - 9999
    volumes:
      - ./docker/wiremock/__files:/home/wiremock/__files
      - ./docker/wiremock/mappings:/home/wiremock/mappings
    entrypoint: [ "/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose" ]
    networks:
      - functional-tests-network

volumes:
  db_data:
networks:
  functional-tests-network:
    driver: bridge
